---
- name: Install Web Server
  apt:
    name: apache2
    state: present
  async: 600
  poll: 1
- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: yes
  async: 600
  poll: 1

- name: Configure Apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes

